openapi: 3.0.1
info:
  title: Expensia server API
  version: '1.0.0'
servers:
  - url: 'http://localhost:8085'
    description: local

paths:
  /board:
    get:
      tags:
        - Board-Service
      operationId: getAllBoards
      description: 'Получить все доски по tgUserId'
      parameters:
        - $ref: '#/components/parameters/tgUserIdHeader'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListBoardBackendResponse'
        '409':
          $ref: '#/components/responses/409'
        '401':
          $ref: '#/components/responses/401'
        '404':
          $ref: '#/components/responses/404'
        '500':
          $ref: '#/components/responses/500'
    post:
      tags:
        - Board-Service
      operationId: createBoard
      description: 'Создать доску'
      parameters:
        - name: name
          schema:
            type: string
          in: query
          required: true
        - name: currency
          schema:
            $ref: '#/components/schemas/CurrencyEnum'
          in: query
          required: true
        - $ref: '#/components/parameters/tgUserIdHeader'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SingleBoardBackendResponse'
        '400':
          $ref: '#/components/responses/400'
        '401':
          $ref: '#/components/responses/401'
        '404':
          $ref: '#/components/responses/404'
        '500':
          $ref: '#/components/responses/500'
  /board/add/participant:
    post:
      tags:
        - Board-Service
      operationId: addParticipantToBoard
      description: 'Добавить участников на доску'
      parameters:
        - $ref: '#/components/parameters/tgUserIdHeader'
        - name: boardId
          schema:
            type: integer
            format: int64
          in: query
          required: true
        - name: participantTgUserIdList
          in: query
          required: true
          schema:
            type: array
            items:
              type: integer
              format: int64
      responses:
        '204':
          description: NO CONTENT
        '401':
          $ref: '#/components/responses/401'
        '404':
          $ref: '#/components/responses/404'
        '500':
          $ref: '#/components/responses/500'
#--------------------------------------------------------------------------------------------------------#
components:
  parameters:
    tgUserIdHeader:
      name: tgUserId
      in: header
      required: true
      schema:
        type: integer
        format: int64
  responses:
    '400':
      description: Bad request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/BackendErrorResponse'
    '409':
      description: Conflict
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/BackendErrorResponse'
    '401':
      description: UNAUTHORIZED
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/BackendErrorResponse'
    404:
      description: NOT_FOUND
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/BackendErrorResponse'
    '500':
      description: Internal Server Error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/BackendErrorResponse'
#--------------------------------------------------------------------------------------------------------#
  schemas:
    BackendErrorResponse:
      type: object
      properties:
        meta:
          $ref: '#/components/schemas/MetaData'
        errorCode:
          type: integer
        description:
          type: string
#--------------------------------------------------------------------------------------------------------#
    MetaData:
      type: object
      properties:
        timestamp:
          type: string
        path:
          type: string
#--------------------------------------------------------------------------------------------------------#
    BasicBackendResponse:
      type: object
      properties:
        meta:
          $ref: '#/components/schemas/MetaData'
        errorCode:
          type: string
        description:
          type: string
#--------------------------------------------------------------------------------------------------------#
    CurrencyEnum:
      type: string
      enum:
        - RUB
        - USD
#--------------------------------------------------------------------------------------------------------#
    SingleBoardBackendResponse:
      allOf:
        - $ref: '#/components/schemas/BasicBackendResponse'
        - type: object
          properties:
            payload:
              $ref: '#/components/schemas/BoardResponse'
    ListBoardBackendResponse:
      allOf:
        - $ref: '#/components/schemas/BasicBackendResponse'
        - type: object
          properties:
            payload:
              type: array
              items:
                $ref: '#/components/schemas/BoardResponse'
#--------------------------------------------------------------------------------------------------------#
    BoardResponse:
      type: object
      properties:
        owner:
          type: integer
          format: int64
        name:
          type: string
        currency:
          type: string
#--------------------------------------------------------------------------------------------------------#