version: '3'
services:

  notebackendapp:
    build:
      context: ./noteBackendApp
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: unless-stopped
    networks:
      - skynet
networks:
  skynet: