// Package http provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.16.3 DO NOT EDIT.
package http

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
)

// BackendErrorResponse defines model for BackendErrorResponse.
type BackendErrorResponse struct {
	Description *string   `json:"description,omitempty"`
	ErrorCode   *int      `json:"errorCode,omitempty"`
	Meta        *MetaData `json:"meta,omitempty"`
}

// BasicBackendResponse defines model for BasicBackendResponse.
type BasicBackendResponse struct {
	Description *string   `json:"description,omitempty"`
	ErrorCode   *string   `json:"errorCode,omitempty"`
	Meta        *MetaData `json:"meta,omitempty"`
}

// CreateAccountRequest defines model for CreateAccountRequest.
type CreateAccountRequest struct {
	Email          *string `json:"email,omitempty"`
	TelegramUserId *int64  `json:"telegramUserId,omitempty"`
	Username       *string `json:"username,omitempty"`
}

// MetaData defines model for MetaData.
type MetaData struct {
	Path      *string `json:"path,omitempty"`
	Timestamp *string `json:"timestamp,omitempty"`
}

// ProfileResponse defines model for ProfileResponse.
type ProfileResponse struct {
	AccountId *int64  `json:"accountId,omitempty"`
	Id        *int64  `json:"id,omitempty"`
	Role      *string `json:"role,omitempty"`
	Username  *string `json:"username,omitempty"`
}

// SingleProfileBackendResponse defines model for SingleProfileBackendResponse.
type SingleProfileBackendResponse struct {
	Description *string          `json:"description,omitempty"`
	ErrorCode   *string          `json:"errorCode,omitempty"`
	Meta        *MetaData        `json:"meta,omitempty"`
	Payload     *ProfileResponse `json:"payload,omitempty"`
}

// SingleUserIdentityBackendResponse defines model for SingleUserIdentityBackendResponse.
type SingleUserIdentityBackendResponse struct {
	Description *string               `json:"description,omitempty"`
	ErrorCode   *string               `json:"errorCode,omitempty"`
	Meta        *MetaData             `json:"meta,omitempty"`
	Payload     *UserIdentityResponse `json:"payload,omitempty"`
}

// UserIdentityResponse defines model for UserIdentityResponse.
type UserIdentityResponse struct {
	Email          *string `json:"email,omitempty"`
	TelegramUserId *int64  `json:"telegramUserId,omitempty"`
}

// N400 defines model for 400.
type N400 = BackendErrorResponse

// N401 defines model for 401.
type N401 = BackendErrorResponse

// N404 defines model for 404.
type N404 = BackendErrorResponse

// N500 defines model for 500.
type N500 = BackendErrorResponse

// RegisterAccountJSONRequestBody defines body for RegisterAccount for application/json ContentType.
type RegisterAccountJSONRequestBody = CreateAccountRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (GET /account/{telegramId})
	GetAccountByTgId(c *gin.Context, telegramId int64)

	// (POST /identity/user/register)
	RegisterAccount(c *gin.Context)

	// (GET /profile/{telegramId})
	GetProfileByTgId(c *gin.Context, telegramId int64)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// GetAccountByTgId operation middleware
func (siw *ServerInterfaceWrapper) GetAccountByTgId(c *gin.Context) {

	var err error

	// ------------- Path parameter "telegramId" -------------
	var telegramId int64

	err = runtime.BindStyledParameter("simple", false, "telegramId", c.Param("telegramId"), &telegramId)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter telegramId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetAccountByTgId(c, telegramId)
}

// RegisterAccount operation middleware
func (siw *ServerInterfaceWrapper) RegisterAccount(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.RegisterAccount(c)
}

// GetProfileByTgId operation middleware
func (siw *ServerInterfaceWrapper) GetProfileByTgId(c *gin.Context) {

	var err error

	// ------------- Path parameter "telegramId" -------------
	var telegramId int64

	err = runtime.BindStyledParameter("simple", false, "telegramId", c.Param("telegramId"), &telegramId)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter telegramId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetProfileByTgId(c, telegramId)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/account/:telegramId", wrapper.GetAccountByTgId)
	router.POST(options.BaseURL+"/identity/user/register", wrapper.RegisterAccount)
	router.GET(options.BaseURL+"/profile/:telegramId", wrapper.GetProfileByTgId)
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xXX2/jRBD/KtHAoy92IKCT35q7AyJEc8o1L6AKLfbE2cPeNbuTk6IoUskh8XISjzzy",
	"FSJQRWlF+Qrrb4R27TQpcXEpoaCKpzi745nfzPzmj+cQySyXAgVpCOegUOdSaHR/ukFgfyIpCAXZR5bn",
	"KY8YcSn8l1oKe6ajCWbMPr2tcAwhvOVvdPrlrfZ7LPoSRfxMKamGlRFYLBYexKgjxXOrE0Losbil8Ksp",
	"aoKFB92gc+8QRocHo6OPBsP+p8+elhi6947hcHD0+QeD0aED8N6/kIe+IFSCpa0XqF6harkXwMpVmqyh",
	"WmXhHHIlc1TESxpdUzwHmuUIIWhSXCTWPbSvP5Exbt1yQZigstcZUqNXnyCxp4yYA1ipkF+8xMiRqMc0",
	"jyqs+4W5uf37KJ8oZIQHUSSngoZVCeygxIzxtBYBYYqJYtlIo+rHVmQsVcaojOb7XfBqgjvVNstZnU91",
	"GK882MGVM5rUw+IZamJZfksTz5Uc8xRvzhMrI3RrF/ltBZVM63P7F4P0goskxcqPGtqxNB2MIfysqVBr",
	"SLvwduM+SyWLm6j3x6jWAD++gl4yCAVxmv1H8G9DanKiVvafLaRdIPaIi7F0FjhZZjlgrp/yCFsHz/vg",
	"wStUumy4nXbQDqx5maNgOYcQ3m0H7Q54rrYcZr/ivj9fY+zHC3uRIO20MDA/mEtzUbwuvjVnxbJ40zK/",
	"uYM35mdzaX40q2JpTs1F8Z27aFHS4jE4+8pNFus7fIhUtaTe7Cjpxw6OYhkSKu1IwK0tV/4elFUCG3Tg",
	"gZ3mXGEMIakpeltzqjmsx971jeSdPU7CZq7XjMXBx+VGENyk/Qqub4U2G0yTbGdr02iS7W4tBX8ua4Uc",
	"OVlikwVVKuHYHvq88tu3Dc5XmHBNqFypSF1HqO/Nqjgxp+Ync1Z8XSyLE3NWnKy5ZAm2Mufm3KyK1+bX",
	"YrnDpWFlYY2i5AZq6sl4tre81s7Rhcvl/1zaI5est4/W7j6q2lrFrLwcN3fuU5ZVxTdmZX4xF3dtW+sB",
	"/CDb1g3bxcNjWeWo5ZX99nAfI2UCr7uZyoil4MFUpRDChCgPfd8dTqSm8HHwuGO3g98DAAD//xUX+JPw",
	"DgAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
