// Package http provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.16.3 DO NOT EDIT.
package http

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
)

// Defines values for CreateAccountRequestAccountType.
const (
	TG  CreateAccountRequestAccountType = "TG"
	WEB CreateAccountRequestAccountType = "WEB"
)

// AccountResponse defines model for AccountResponse.
type AccountResponse struct {
	Email            *string `json:"email,omitempty"`
	FirstName        *string `json:"firstName,omitempty"`
	Id               *int64  `json:"id,omitempty"`
	KeycloakId       *string `json:"keycloakId,omitempty"`
	LastName         *string `json:"lastName,omitempty"`
	TelegramId       *int64  `json:"telegramId,omitempty"`
	TelegramUserName *string `json:"telegramUserName,omitempty"`
	Username         *string `json:"username,omitempty"`
}

// BackendErrorResponse defines model for BackendErrorResponse.
type BackendErrorResponse struct {
	Description *string   `json:"description,omitempty"`
	ErrorCode   *int      `json:"errorCode,omitempty"`
	Meta        *MetaData `json:"meta,omitempty"`
}

// BasicBackendResponse defines model for BasicBackendResponse.
type BasicBackendResponse struct {
	Description *string   `json:"description,omitempty"`
	ErrorCode   *string   `json:"errorCode,omitempty"`
	Meta        *MetaData `json:"meta,omitempty"`
}

// CreateAccountRequest defines model for CreateAccountRequest.
type CreateAccountRequest struct {
	AccountType      *CreateAccountRequestAccountType `json:"accountType,omitempty"`
	Email            *string                          `json:"email,omitempty"`
	FirstName        *string                          `json:"firstName,omitempty"`
	LastName         *string                          `json:"lastName,omitempty"`
	TelegramId       *int64                           `json:"telegramId,omitempty"`
	TelegramUserName *string                          `json:"telegramUserName,omitempty"`
	Username         *string                          `json:"username,omitempty"`
}

// CreateAccountRequestAccountType defines model for CreateAccountRequest.AccountType.
type CreateAccountRequestAccountType string

// MetaData defines model for MetaData.
type MetaData struct {
	Path      *string `json:"path,omitempty"`
	Timestamp *string `json:"timestamp,omitempty"`
}

// ProfileResponse defines model for ProfileResponse.
type ProfileResponse struct {
	AccountId *int64  `json:"accountId,omitempty"`
	Id        *int64  `json:"id,omitempty"`
	Role      *string `json:"role,omitempty"`
	Username  *string `json:"username,omitempty"`
}

// SingleAccountBackendResponse defines model for SingleAccountBackendResponse.
type SingleAccountBackendResponse struct {
	Description *string          `json:"description,omitempty"`
	ErrorCode   *string          `json:"errorCode,omitempty"`
	Meta        *MetaData        `json:"meta,omitempty"`
	Payload     *AccountResponse `json:"payload,omitempty"`
}

// SingleProfileBackendResponse defines model for SingleProfileBackendResponse.
type SingleProfileBackendResponse struct {
	Description *string          `json:"description,omitempty"`
	ErrorCode   *string          `json:"errorCode,omitempty"`
	Meta        *MetaData        `json:"meta,omitempty"`
	Payload     *ProfileResponse `json:"payload,omitempty"`
}

// N400 defines model for 400.
type N400 = BackendErrorResponse

// N401 defines model for 401.
type N401 = BackendErrorResponse

// N404 defines model for 404.
type N404 = BackendErrorResponse

// N500 defines model for 500.
type N500 = BackendErrorResponse

// RegisterAccountJSONRequestBody defines body for RegisterAccount for application/json ContentType.
type RegisterAccountJSONRequestBody = CreateAccountRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (POST /account)
	RegisterAccount(c *gin.Context)

	// (GET /account/{telegramId})
	GetAccountByTgId(c *gin.Context, telegramId int64)

	// (GET /profile/{telegramId})
	GetProfileByTgId(c *gin.Context, telegramId int64)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// RegisterAccount operation middleware
func (siw *ServerInterfaceWrapper) RegisterAccount(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.RegisterAccount(c)
}

// GetAccountByTgId operation middleware
func (siw *ServerInterfaceWrapper) GetAccountByTgId(c *gin.Context) {

	var err error

	// ------------- Path parameter "telegramId" -------------
	var telegramId int64

	err = runtime.BindStyledParameter("simple", false, "telegramId", c.Param("telegramId"), &telegramId)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter telegramId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetAccountByTgId(c, telegramId)
}

// GetProfileByTgId operation middleware
func (siw *ServerInterfaceWrapper) GetProfileByTgId(c *gin.Context) {

	var err error

	// ------------- Path parameter "telegramId" -------------
	var telegramId int64

	err = runtime.BindStyledParameter("simple", false, "telegramId", c.Param("telegramId"), &telegramId)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter telegramId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetProfileByTgId(c, telegramId)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.POST(options.BaseURL+"/account", wrapper.RegisterAccount)
	router.GET(options.BaseURL+"/account/:telegramId", wrapper.GetAccountByTgId)
	router.GET(options.BaseURL+"/profile/:telegramId", wrapper.GetProfileByTgId)
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+yX34/bRBDH/5Vo4NGKHQio8tulPUqESKprIiSqCC32xNmevWt2N5WiyNJxReKlEo88",
	"8i9EoIqjJ8q/sP6P0K7t/GicS3SEcjrxdL7d9czXM5+dmcwh4EnKGTIlwZ+DQJlyJtH+0/Y88yfgTCFT",
	"5pGkaUwDoihn7nPJmVmTwQQTYp4+FDgGHz5wVzbdYle6HRKcIwtPheDirHQCWZY5EKIMBE2NTfChQ8KG",
	"wO+mKBVkDrS91nuXMOydDAef98+6X58+KjS037uGXn/wzWf9Yc8K+OQ/yEOXKRSMxI2nKF6gaNgXwJwr",
	"LRlHJ0HAp0wt7fhzSAVPUShaEIQJobF5ULMUwQepBGWR+aYxFVL1SIK1uzQ0y2MuEqLAB8rUp21wqnOU",
	"KYxQmIPnOAtiTs67Ya2dmNzgRGGMkSBJ91Bn1QtDiWKn1ak0cavdzJZG+bfPMbCA1+ZjK44bualxiub1",
	"hzxc97omPEG1F4wvUZFHRJFdMiUNSq3Hlbna/ecqHwokCpdUFlVkSyUp9gf27TkgmybgP4PBY3Dgq9MO",
	"jJwa5bcE+e4DuIzoVpxSoib1ummCUpEkPdDFE8HHNMbd3JQZOTgOB5cHweOjBOkpZVFcgVVzDUgc98fg",
	"P9tXe2suUeZsx30WcxLuuwrvFt8a4aOl9DIFd0T6u0DUSjeLlI25TRFVJpFgwLcdiQbYOHnSBQdeoJBF",
	"y2o1vaZnssVTZCSl4MPHTa/ZAseibAW6JWpWLC+qw2bj0z/rRX6hX+vf9FX+fX6ZX+ir/EK/1b/qRX6Z",
	"v2rohX6j3+hF/lL/mV+CdSdsKzb8whlGVCoUZXrAgXKc6fBwdrQ2XlvpMhuzjRHuoyOODjdegpoRov9F",
	"MT15uwwvlbrm0Gra23e2tTaV7TvbXhugbj5rDlkQSSRNP6gSODKLFTfufFW0M2MzwjqGftFv9XX+Mv9R",
	"XxXM/GUXXunfK5D0a32d/2Q3Gipq0HALpMeoqljPBlE3tBgLkqBCIe2FpcaXrdIOFMVsvaUU4FGBIfhK",
	"TNFZS/Pe0pmN/gfp3wEpLWrfrUEytSj/QS/0H/r6tlxV3eBecrWj1d0/rsoPhaJVSvs7rUjg5mfGPCAx",
	"ODAVMfgwUSr1XdcuTrhU/gPvQcv0278DAAD//2EHuGILEAAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
