openapi: 3.0.1
info:
  title: User Service API
  version: '1.0.0'
servers:
  - url: 'http://localhost:8081'
    description: local

paths:
  /identity/user/register:
    post:
      tags:
        - User-Identity-Service
      operationId: registerAccount
      description: 'Зарегистрировать аккаунт'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateAccountRequest'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SingleUserIdentityBackendResponse'
        '409':
          $ref: '#/components/responses/409'
        '401':
          $ref: '#/components/responses/401'
        '500':
          $ref: '#/components/responses/500'
  /account/{telegramId}:
    get:
      tags:
        - Account
      operationId: getAccountByTgId
      description: 'Получить пользователя по tg id'
      parameters:
        - name: telegramId
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SingleUserIdentityBackendResponse'
        '400':
          $ref: '#/components/responses/400'
        '401':
          $ref: '#/components/responses/401'
        '404':
          $ref: '#/components/responses/404'
        '500':
          $ref: '#/components/responses/500'
#--------------------------------------------------------------------------------------------------------#
  /profile/{telegramId}:
    get:
      tags:
        - Profile
      operationId: getProfileByTgId
      description: 'Получить профайл пользователя по tg id'
      parameters:
        - name: telegramId
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SingleProfileBackendResponse'
        '400':
          $ref: '#/components/responses/400'
        '401':
          $ref: '#/components/responses/401'
        '404':
          $ref: '#/components/responses/404'
        '500':
          $ref: '#/components/responses/500'
  #--------------------------------------------------------------------------------------------------------#
components:
  responses:
    '409':
      description: Conflict
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/BackendErrorResponse'
    '401':
      description: UNAUTHORIZED
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/BackendErrorResponse'
    404:
      description: NOT_FOUND
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/BackendErrorResponse'
    '500':
      description: Internal Server Error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/BackendErrorResponse'
#--------------------------------------------------------------------------------------------------------#
  schemas:
    BackendErrorResponse:
      type: object
      properties:
        meta:
          $ref: '#/components/schemas/MetaData'
        errorCode:
          type: integer
        description:
          type: string
#--------------------------------------------------------------------------------------------------------#
    MetaData:
      type: object
      properties:
        timestamp:
          type: string
        path:
          type: string
#--------------------------------------------------------------------------------------------------------#
    BasicBackendResponse:
      type: object
      properties:
        meta:
          $ref: '#/components/schemas/MetaData'
        errorCode:
          type: string
        description:
          type: string
#--------------------------------------------------------------------------------------------------------#
    CreateAccountRequest:
      type: object
      properties:
        email:
          type: string
        username:
          type: string
        telegramUserId:
          type: integer
          format: int64
#--------------------------------------------------------------------------------------------------------#
    UserIdentityResponse:
      type: object
      properties:
        email:
          type: string
        telegramUserId:
          type: integer
          format: int64
#--------------------------------------------------------------------------------------------------------#
    SingleUserIdentityBackendResponse:
      allOf:
        - $ref: '#/components/schemas/BasicBackendResponse'
        - type: object
          properties:
            payload:
              $ref: '#/components/schemas/UserIdentityResponse'
    ListUserIdentityBackendResponse:
      allOf:
        - $ref: '#/components/schemas/BasicBackendResponse'
        - type: object
          properties:
            payload:
              type: array
              items:
                $ref: '#/components/schemas/UserIdentityResponse'
#--------------------------------------------------------------------------------------------------------#
    SingleProfileBackendResponse:
      allOf:
        - $ref: '#/components/schemas/BasicBackendResponse'
        - type: object
          properties:
            payload:
              $ref: '#/components/schemas/ProfileResponse'
    ListProfileBackendResponse:
      allOf:
        - $ref: '#/components/schemas/BasicBackendResponse'
        - type: object
          properties:
            payload:
              type: array
              items:
                $ref: '#/components/schemas/ProfileResponse'
#--------------------------------------------------------------------------------------------------------#
    ProfileResponse:
      type: object
      properties:
        id:
          type: integer
          format: int64
        accountId:
          type: integer
          format: int64
        role:
          type: string
        username:
          type: string
#--------------------------------------------------------------------------------------------------------#