keycloak:
  keycloakUrl: "http://keycloak:7080/realms/home-system/protocol/openid-connect"
  keycloakHost: "http://keycloak:7080"
  keycloakRealm: "home-system"
  tokenUrl: "/token"
  clientId: "d3f1202c-d7d6-4694-9a6c-6e1575321baf"
  clientSecret: "W2aXh7r5NrGPPROdgS1x1Ic5cMXqCZHx"
  serverGrantType: "client_credentials"

database:
  host: "postgresServer"
  user: "postgres"
  password: "root"
  dataBaseName: "auth"
  dialect: "postgres"
  impl: "sqlx"

server:
  name: "auth backend server"
  port: 8081