botToken: "8193938957:AAEh3-Yu8h0TPCri1HBpm6VfEa2ewqugQBQ"
handlersToInit: [StartCommandHandler,TutorialCommandHandler,MenuCommandHandler,NoteCommandHandler,ProfileCommandHandler]
authServerUrl: "http://localhost:8081"
noteBackendUrl: "http://localhost:8080"