server:
  botToken: "7553203004:AAE7nqBQfz7sRzEDwg0L4VIbUzriDjDFL1I"
  handlersToInit: [StartCommandHandler,NoteCommandHandler,MenuCommandHandler,TutorialCommandHandler,ProfileCommandHandler]
  authServerUrl: "http://localhost:8081"
  noteBackendUrl: "http://localhost:8080"

database:
  host: "localhost"
  user: "telegram_bot_user"
  password: "9876c88e-94a6-45c0-8e88-161d7519bf12"
  dataBaseName: "telegram_bot"
  dialect: "postgres"
  impl: "sqlx"