# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Build noteBackend APP

on:
  push:
    branches: [ "master","dev"]
  pull_request:
    branches: [ "master","dev"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23.0'
    - name: Generate API
      run: |
        cd noteBackend/api/spec
        go install github.com/oapi-codegen/oapi-codegen/v2/cmd/oapi-codegen@latest
        oapi-codegen -package=generatedApi -generate "types,spec,gin" note-api.yml > note-api.gen.go
        echo 'authBackend api is Done'

    - name: Build
      run: |
        cd noteBackend/cmd
        go get .
        go mod verify
        cd ..
        go build -v ./...

    - name: Test
      run: |
        cd noteBackend/cmd
        go test -v ./...
